import turtle
# First initial
turtle.width(10)
turtle.colormode(255)
turtle.color(173, 50, 60)

turtle.forward(50)
turtle.penup()
turtle.backward(50)
turtle.right(90)
turtle.pendown()
turtle.forward(50)
turtle.left(90)
turtle.forward(25)
turtle.penup()
turtle.backward(25)
turtle.pendown()
turtle.right(90)
turtle.forward(50)
turtle.left(90)
turtle.forward(50)
turtle.penup()
# Last inital

turtle.backward(50)
turtle.right(90)
turtle.backward(100)
turtle.left(90)
turtle.forward(100)
turtle.pendown()
turtle.right(90)
turtle.forward(50)
turtle.left(45)
turtle.forward(65)
turtle.penup()
turtle.backward(65)
turtle.pendown()
turtle.left(90)
turtle.forward(65)
turtle.penup()
turtle.backward(65)
turtle.pendown()
turtle.right(135)
turtle.forward(50)
turtle.exitonclick()